<?php

namespace Tests;


use PHPUnit\Framework\TestCase;

class SimpleTest extends TestCase
{
    use HTTP;

    protected $userId;
    protected $oUser;

//    public function setUp()
//    {
//        parent::setUp(); // TODO: Change the autogenerated stub
//        $this->userId = 1;
//        $this->oUser = new \WP_User($this->userId);
//        wp_set_current_user($this->userId);
//    }

    public function testTrueIsTrue()
    {
//        $aResponse1 = $this->post(['username' => 'wiloke1', 'action' => 'login']);
        $this->assertTrue(true);
    }
}
