<?php

namespace Tests;


use PHPUnit\Framework\TestCase;

class SimpleTest extends TestCase
{
    use HTTP;

    protected $userId;
    protected $oUser;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->oUser = get_user_by('login', 'admin');
        var_export($this->oUser);die;
        $this->userId = $this->oUser->ID;
        wp_set_current_user($this->userId);
    }

    public function testTrueIsTrue()
    {
        $aResponse = $this->post([
            'action' => 'login',
            'username' => 'wiloke'
        ]);

        $this->assertTrue($aResponse['success']);
    }
}
