version: 2.0

references:
  # Environment variables
  #
  WP_CORE_DIR: &WP_CORE_DIR
                 /tmp/wordpress
  WP_HOST: &WP_HOST
             wiloke-dev-ops.test
  WP_ORG_PLUGIN_NAME: &WP_ORG_PLUGIN_NAME
                        devops
  WP_ORG_USERNAME: &WP_ORG_USERNAME
                     carlalexander

  # Default container configuration
  #
  container_config: &container_config
    docker:
      - image: circleci/php:7.2
      - image: circleci/mysql:5.7
        enviroment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
    working_directory: ~/devops

  workspace_root: &workspace_root
                    /tmp

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  # Default configuration for all phpunit testing jobs
  #
  phpunit_job: &phpunit_job
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Run PHP unit tests
          command: vendor/bin/phpunit

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: composer install -n -o
      - run:
          name: Install WordPress
          command: bash .circleci/install-wp.sh
      - persist_to_workspace:
          root: .
          paths:
            - vendor
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - wordpress

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
