version: 2.0

references:
  # Environment variables
  #
  WP_CORE_DIR: &WP_CORE_DIR
                 /tmp/wordpress
  WP_HOST: &WP_HOST
             wiloke-dev-ops.test
  WP_ORG_PLUGIN_NAME: &WP_ORG_PLUGIN_NAME
                        devops
  WP_ORG_USERNAME: &WP_ORG_USERNAME
                     carlalexander

  # Default container configuration
  #
  container_config: &container_config
    docker:
      - image: circleci/php:7.2
        enviroment:
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
    working_directory: ~/devops

  workspace_root: &workspace_root
                    /tmp

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  copy_vendor: &copy_vendor
    run:
      name: Copy vendor directory
      command: cp -R /tmp/vendor .

  # Default configuration for all behat testing jobs
  #
  behat_job: &behat_job
    <<: *container_config
    docker:
      - image: circleci/php:7.2
      - image: circleci/mysql:5.7
        enviroment:
          MYSQL_ROOT_PASSWORD: root
    steps:
      - checkout
      - run:
          name: Add WordPress host to hosts file
          command: echo "127.0.0.1 ${WP_HOST}" | sudo tee -a /etc/hosts
      - *attach_workspace
      - *copy_vendor
      - run:
          name: Install MySQL client
          command: sudo apt-get install mysql-client
      - run:
          name: Install MySQL PHP extension
          command: sudo docker-php-ext-install mysqli
      - run:
          name: Setup WordPress
          command: .circleci/setup-$WP_TYPE.sh
      - run:
          name: Start PHP server
          command: sudo php -S $WP_HOST:80 -t $WP_CORE_DIR
          background: True
      - run:
          name: Run Behat tests
          command: vendor/bin/behat --config .circleci/behat.yml --format progress --tags=$WP_TYPE

  # Default configuration for all phpunit testing jobs
  #
  phpunit_job: &phpunit_job
    steps:
      - checkout
      - *attach_workspace
      - *copy_vendor

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Update Composer
          command: sudo composer self-update
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
            - composer-v1-
      - run:
          name: Installing Composer
          command: composer install -n --prefer-dist
      - run:
          name: Install WordPress
          command: bash .circleci/install-wp.sh
      - run:
         name: Create a folder
         command: mkdir myfolder
      - run:
          name: Create a file in the folder
          command: touch myfolder/index.php
      - persist_to_workspace:
          root: .
          paths:
            - myfolder
      - persist_to_workspace:
          root: .
          paths:
            - vendor
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - wordpress
  test_php72:
    <<: *phpunit_job
    docker:
      - image: circleci/php:7.2
  acceptance_singlesite:
    <<: *behat_job
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_TYPE: singlesite

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test_php72:
          requires:
            - build
      - acceptance_singlesite:
          requires:
            - test_php72
